#!/bin/bash
# Demo script showing what the new install-systemd.sh prompts look like
# (This is just for demonstration - doesn't actually install anything)

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}Penguin Overlord - systemd Installer${NC}"
echo "Project: /home/chiefgyk3d/src/penguin-overlord"
echo "User: chiefgyk3d"
echo ""
echo "Choose deployment mode:"
echo "  1) Python (virtual environment)"
echo "  2) Docker (container)"
echo "Select [1-2]: 1"
echo ""

echo -e "${BLUE}News System Configuration:${NC}"
echo "The bot includes news aggregation for 73 sources across 5 categories."
echo ""
echo "Choose news fetching strategy:"
echo -e "  1) ${GREEN}Integrated${NC} - News runs inside bot (simpler, 500MB RAM constant)"
echo -e "  2) ${GREEN}Optimized${NC}  - Separate systemd timers (99% less bandwidth, 0MB idle)"
echo ""
echo "Select [1-2] (default: 1): 2"
echo ""
echo -e "${GREEN}✓${NC} Will deploy optimized news timers"
echo ""
echo "... (Python setup continues) ..."
echo ""

echo -e "${BLUE}Deploying Optimized News Timers...${NC}"
echo "  ✓ Created penguin-news-cve.service"
echo "  ✓ Created penguin-news-cve.timer"
echo "  ✓ Created penguin-news-cybersecurity.service"
echo "  ✓ Created penguin-news-cybersecurity.timer"
echo "  ✓ Created penguin-news-tech.service"
echo "  ✓ Created penguin-news-tech.timer"
echo "  ✓ Created penguin-news-gaming.service"
echo "  ✓ Created penguin-news-gaming.timer"
echo "  ✓ Created penguin-news-apple_google.service"
echo "  ✓ Created penguin-news-apple_google.timer"
echo -e "${GREEN}✓${NC} All news timers created"
echo "Enable and start news timers? (Y/n) Y"
echo -e "${GREEN}✓${NC} News timers enabled and started"
echo ""

echo -e "${GREEN}Installation Complete!${NC}"
echo ""
echo "Main Bot Commands:"
echo "  sudo systemctl start|stop|restart|status penguin-overlord"
echo "  sudo journalctl -u penguin-overlord -f"
echo ""
echo -e "${BLUE}News Timer Commands:${NC}"
echo "  sudo systemctl list-timers penguin-news-*           # View schedule"
echo "  sudo systemctl status penguin-news-cybersecurity    # Check status"
echo "  sudo journalctl -u penguin-news-tech -f             # View logs"
echo "  sudo systemctl start penguin-news-cve.service       # Manual run"
echo ""
echo -e "${YELLOW}Note: Configure news channels in Discord:${NC}"
echo "  /news set_channel cybersecurity #security-news"
echo "  /news set_channel tech #tech-news"
echo "  /news set_channel gaming #gaming-news"
echo "  /news set_channel apple_google #apple-google-news"
echo "  /news set_channel cve #security-alerts"
echo ""
echo -e "${GREEN}News Schedule:${NC}"
echo "  CVE:           Every 6 hours at :00"
echo "  Cybersecurity: Every 3 hours at :01"
echo "  Tech:          Every 4 hours at :30"
echo "  Gaming:        Every 2 hours at :15"
echo "  Apple/Google:  Every 3 hours at :45"
